# Local development configuration
# This overrides _config.yml for local development

# Override baseurl for local development
baseurl: ""
url: "http://localhost:4000"

# All other settings inherit from _config.yml
