# Site settings
title: Harry Luo
author: Harry Luo
email: your-email@example.com
description: >-
  A personal blog and portfolio using the Hamilton theme.

# Build settings
theme: minima

# URL settings (for GitHub Pages)
url: "https://harryluoo.github.io"
baseurl: ""

# Social media links in the footer
social_links:
  github: HarryLuoo
  # twitter: your-username
  # linkedin: your-username
  # Add other social media platforms as needed

# Jekyll settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# Hamilton theme settings
skin: daylight

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
