backend:
  name: github
  repo: HarryLuoo/harryluoo.github.io
  branch: main

media_folder: "assets/img" # Define where the media files will be stored
public_folder: "/assets/img" # The src attribute for the media file

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Attachment", name: "attachment", widget: "file", required: false}
      
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "About Page"
        name: "about"
        file: "about.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "string", default: "/about/"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Categories Page"
        name: "categories"
        file: "categories.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "archive"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Tags Page"
        name: "tags"
        file: "tags.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "archive"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "navigation"
    label: "Navigation"
    files:
      - label: "Main Navigation"
        name: "main"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation Links"
            name: "links"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
